### ISSUE TITLE
Would you like to add the implementation of PortraitFCN+ ?

### ISSUE THREAD

**Issue by liuruoze** [Corea/automatic-portrait-tf#1]
This is a nice work ! I have used it to train my model and it works well. 

But this project seem to be an implementation of PortraitFCN, not PortraitFCN+. It was great if you would like to add the implementation the PortraitFCN+ and we could get a better portrait segmentation model.

**Comment by Corea** [comment]
Sorry, I don't have a plan to implement PortraitFCN+.
